name: Deploy to Vercel

# 自动部署触发条件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 设置Node.js环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # 安装Vercel CLI
    - name: Install Vercel CLI
      run: npm install -g vercel@latest

    # 部署到Vercel (预览)
    - name: Deploy to Vercel Preview
      if: github.event_name == 'pull_request'
      run: vercel --token=${{ secrets.VERCEL_TOKEN }} --confirm
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    # 部署到Vercel (生产)
    - name: Deploy to Vercel Production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    # 通知部署状态
    - name: Deploy Status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ 部署成功到Vercel"
        else
          echo "❌ 部署失败"
        fi